# This file should be at the ROOT of your project folder.

# [build] context: settings for production builds
[build]
  # Base directory: All commands will run from this directory.
  # This tells Netlify to 'cd' into 'frontend' before doing anything else.
  base = "frontend"

  # Build command: This is run from the 'base' directory.
  command = "npm run build"

  # Publish directory: This is where the built files are, relative to the 'base' directory.
  publish = "dist"

# [[redirects]] context: settings for proxying API requests
[[redirects]]
  from = "/api/*"
  to = "https://njtwebgm.onrender.com/api/:splat"
  status = 200
