# This file should be at the ROOT of your project folder.

[build]
  # Explicitly tell Netlify to build inside the frontend folder
  command = "npm --prefix frontend run build"
  
  # The location of the built site, relative to the project root
  publish = "frontend/dist"

# This rule tells Netlify how to handle API requests
[[redirects]]
  from = "/api/*"
  to = "https://njtwebgm.onrender.com/api/:splat"
  status = 200
