[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"   # change to "build" if CRA

[[redirects]]
  from = "/api/*"
  to = "https://njtwebgm.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
