# This file should be at the ROOT of your project folder.

# This tells Netlify how to build the project explicitly.
[build]
  # 1. Change directory into the 'frontend' folder, then run the build command.
  command = "cd frontend && npm run build"
  # 2. Specify the location of the built site, relative to the project root.
  publish = "frontend/dist"

# This rule tells Netlify how to handle API requests
[[redirects]]
  from = "/api/*"
  to = "https://njtwebgm.onrender.com/api/:splat"
  status = 200
