# This file should be at the ROOT of your project folder.

[build]
  # Tell Netlify that all build-related commands and paths
  # should be run from within the 'frontend' directory.
  base    = "frontend"
  
  # The command to build the site. Since the 'base' is set,
  # Netlify is already in the 'frontend' directory.
  command = "npm run build"
  
  # The location of the built site, relative to the 'base' directory.
  publish = "dist"

# This rule tells Netlify how to handle API requests
[[redirects]]
  from = "/api/*"
  to = "https://njtwebgm.onrender.com/api/:splat"
  status = 200
